### PR TITLE
Fixed the short URL links and added a Stats Page

### LINKED ISSUE #6: Device and Browser Tracking
Enhancement suggestion from the poster:

Enhance analytics by tracking users devices and browsers, providing deeper insights into how and where links are accessed.

### LINKED ISSUE #12: Fix the Short URL links
Fix the short URLs in the Manage your URLs page.

### PR DESCRIPTION
**Pull request by AdrYne01**
A very small fix for the short URL links in the Mange your URLs page.

### CODE REVIEW

**Comment by bradenhelmer** [comment]
is this to open up the link? it's still giving me an error clicking on either the long or short url

**Comment by AdrYne01** [comment]
https://github.com/user-attachments/assets/aed4b514-bc1b-4099-bc3e-a2735e4dde8d

It didnt work for facebook.com. I am not sure why.

**Comment by AdrYne01** [comment]
https://github.com/user-attachments/assets/a5e4fd6c-ce14-4738-bfcc-9ba35bd30b5f

Stats Page with Device and Browser Info

**Review by bradenhelmer — APPROVED** [review]
Looks great. This will get good points on the "innovation" he mentioned in class. Lets keep smashing out these features and we can worry about tests later.

**Pull request merged**
